---
title: "Useful Latex Code"
author: "Robert Gulotty"
date: "September 20, 2016"
output: html_document
---

Math is easy to print in R Markdown.  For in-line math, you just need to place \$ on each side of your code, as follows:

```$e ^{i \pi}=-1$``` 

The following is the Euler equation: $e^{i \pi}=-1 $

For display math, you just need to place \$\$ on each side of your code, as follows:

```$$e^{i \pi}=-1$$``` 

$$e^{i \pi}=-1 $$

In order to print R code, we enclose our code in 3 left sided quotation marks, with the letter r in curly braces.  

```{r}
sum(c(1:10))
```

Below is a list of some of the most useful math commands:

### Math

Partial derivative $\partial$ : ```\partial```

Real numbers $\Re$ or $\mathbb{R}$ : ```\Re```, ```\mathbb{R}```

### OPERATORS

minimum $\min$ : ```\min```

maxima $\max$ : ```\max```

Superscript $A^{x}$ : ```A^{x}```

Subscript $A_{x}$ : ```A_{x}```

Fractions $\frac{A}{B}$ : ```\frac{A}{B}```

Square Roots $\sqrt{x}$ : ```\sqrt{x}```

Summation $\sum_{i=1}^{n}$ : ```\sum_{i=1}^{n}```

Integration $\int_{0}^{\infty}$ : ```\int_{0}^{\infty}```

Product $\prod_{i=1}^{n}$ : ```\prod_{i=1}^{n}```

### LOGIC

For all $\forall$ : ```\forall```

There exists $\exists$ : ```\exists```

Empty set $\varnothing$ : ```\varnothing```

Coin sample space $\Omega = \{H, T \}$ : ```\Omega = \{H, T \}```

### BINARY LOGIC

Is an element of $\in$ : ```\in```

Is not an element of $\notin$ : ```\notin```

Union $\cup$ : ```\cup```

Intersection $\cap$ : ```\cap```

Less than or equal to $\le$ :```\le```

### GREEK

$\alpha\beta\gamma\delta\epsilon\zeta\eta\theta\iota\kappa\lambda\mu\nu\xi\pi\rho\sigma\tau\upsilon\phi\chi\psi\omega$
```\alpha\beta\gamma\delta\epsilon\zeta\eta\theta\iota\kappa\lambda\mu\nu\xi\pi\rho\sigma\tau\upsilon\phi\chi\psi\omega```

### Examples

- The Three Axioms of Probability

1. $P(E)\in \mathbb{R},\ P(E)\geq 0$  $\forall E \in F$
2. $P(\Omega)=1$
3. $P(E_1 \cup E_2 \cup ... )=\sum_{i=1}^{\infty} P(E_i)$

- Law of Total Probability

$$P(A)=\sum_n P(A|B_n)P(B_n)$$

- Formula for Ordinary Least Squares estimate of $\beta$

$$\hat{\beta}=(X'X)^{-1}X'y$$

- Normal distribution $N(\mu, \sigma)$

$$f(x, \mu, \sigma)= \frac{1}{\sigma\sqrt{2\pi}}e^{-\frac{(x-\mu)^2}{2\sigma^2}}$$
